import type {
  Activity,
  Comment,
  Cycle,
  Issue,
  IssuePriority,
  IssueStatus,
  Label,
  Notification,
  Project,
  Team,
  View,
  Webhook,
  WikiPage,
} from '@keelboard/shared';
import { isoDaysAgo } from '../lib/ids.js';
import type { Store, StoredUser } from './types.js';

const PASSWORD = 'keelboard';

const users: StoredUser[] = [
  {
    id: 'usr_maya',
    name: 'Maya Chen',
    email: 'maya@harbor.studio',
    handle: 'maya',
    role: 'owner',
    title: 'Head of Product',
    teamId: 'team_product',
    avatarHue: 262,
    createdAt: isoDaysAgo(400),
    password: PASSWORD,
  },
  {
    id: 'usr_jonah',
    name: 'Jonah Reed',
    email: 'jonah@harbor.studio',
    handle: 'jonah',
    role: 'admin',
    title: 'Engineering Manager',
    teamId: 'team_platform',
    avatarHue: 204,
    createdAt: isoDaysAgo(380),
    password: PASSWORD,
  },
  {
    id: 'usr_priya',
    name: 'Priya Shah',
    email: 'priya@harbor.studio',
    handle: 'priya',
    role: 'member',
    title: 'Staff Engineer, Navigator',
    teamId: 'team_product',
    avatarHue: 152,
    createdAt: isoDaysAgo(300),
    password: PASSWORD,
  },
  {
    id: 'usr_elias',
    name: 'Elias Ward',
    email: 'elias@harbor.studio',
    handle: 'elias',
    role: 'member',
    title: 'API Engineer',
    teamId: 'team_platform',
    avatarHue: 18,
    createdAt: isoDaysAgo(260),
    password: PASSWORD,
  },
  {
    id: 'usr_noor',
    name: 'Noor Alvi',
    email: 'noor@harbor.studio',
    handle: 'noor',
    role: 'member',
    title: 'Mobile Engineer',
    teamId: 'team_mobile',
    avatarHue: 328,
    createdAt: isoDaysAgo(210),
    password: PASSWORD,
  },
  {
    id: 'usr_theo',
    name: 'Theo Park',
    email: 'theo@harbor.studio',
    handle: 'theo',
    role: 'member',
    title: 'Product Designer',
    teamId: 'team_product',
    avatarHue: 42,
    createdAt: isoDaysAgo(190),
    password: PASSWORD,
  },
  {
    id: 'usr_samir',
    name: 'Samir Cole',
    email: 'samir@harbor.studio',
    handle: 'samir',
    role: 'member',
    title: 'Platform Engineer',
    teamId: 'team_platform',
    avatarHue: 88,
    createdAt: isoDaysAgo(140),
    password: PASSWORD,
  },
  {
    id: 'usr_wren',
    name: 'Wren Solis',
    email: 'wren@harbor.studio',
    handle: 'wren',
    role: 'member',
    title: 'Observability Engineer',
    teamId: 'team_platform',
    avatarHue: 196,
    createdAt: isoDaysAgo(90),
    password: PASSWORD,
  },
];

const teams: Team[] = [
  {
    id: 'team_product',
    key: 'PRD',
    name: 'Product',
    description: 'Navigator, design, and the customer-facing surface.',
    color: '#5e6ad2',
  },
  {
    id: 'team_platform',
    key: 'PLT',
    name: 'Platform',
    description: 'API, billing, and the systems that keep the lights on.',
    color: '#26b5ce',
  },
  {
    id: 'team_mobile',
    key: 'MOB',
    name: 'Mobile',
    description: 'Driftwood iOS and Android.',
    color: '#4cb782',
  },
];

const projects: Project[] = [
  {
    id: 'prj_nav',
    key: 'NAV',
    name: 'Navigator',
    color: '#5e6ad2',
    description: 'The customer web app. Routing, search, and the trip canvas.',
    teamId: 'team_product',
    leadId: 'usr_priya',
    status: 'active',
  },
  {
    id: 'prj_lth',
    key: 'LTH',
    name: 'Lighthouse',
    color: '#26b5ce',
    description: 'Public REST API, partner tokens, and outbound webhooks.',
    teamId: 'team_platform',
    leadId: 'usr_elias',
    status: 'active',
  },
  {
    id: 'prj_keel',
    key: 'KEEL',
    name: 'Keel',
    color: '#f2c94c',
    description: 'Billing, seats, and workspace administration.',
    teamId: 'team_platform',
    leadId: 'usr_samir',
    status: 'active',
  },
  {
    id: 'prj_dft',
    key: 'DFT',
    name: 'Driftwood',
    color: '#4cb782',
    description: 'Native mobile clients.',
    teamId: 'team_mobile',
    leadId: 'usr_noor',
    status: 'active',
  },
  {
    id: 'prj_mar',
    key: 'MAR',
    name: 'Marina',
    color: '#eb5757',
    description: 'Internal admin for support and ops.',
    teamId: 'team_product',
    leadId: 'usr_maya',
    status: 'active',
  },
  {
    id: 'prj_bcn',
    key: 'BCN',
    name: 'Beacon',
    color: '#f2994a',
    description: 'Metrics, traces, and the status page.',
    teamId: 'team_platform',
    leadId: 'usr_wren',
    status: 'active',
  },
];

const labels: Label[] = [
  { id: 'lbl_bug', name: 'bug', color: '#eb5757', projectId: null },
  { id: 'lbl_feat', name: 'feature', color: '#5e6ad2', projectId: null },
  { id: 'lbl_debt', name: 'debt', color: '#9b51e0', projectId: null },
  { id: 'lbl_sec', name: 'security', color: '#f2994a', projectId: null },
  { id: 'lbl_ux', name: 'ux', color: '#27ae60', projectId: null },
  { id: 'lbl_perf', name: 'perf', color: '#26b5ce', projectId: null },
  { id: 'lbl_api', name: 'api', color: '#2d9cdb', projectId: 'prj_lth' },
  { id: 'lbl_ios', name: 'ios', color: '#a0a4ad', projectId: 'prj_dft' },
  { id: 'lbl_and', name: 'android', color: '#4cb782', projectId: 'prj_dft' },
  { id: 'lbl_bill', name: 'billing', color: '#f2c94c', projectId: 'prj_keel' },
];

const cycles: Cycle[] = [
  {
    id: 'cyc_nav_23',
    projectId: 'prj_nav',
    projectKey: 'NAV',
    name: 'Navigator Cycle 23',
    goal: 'Ship saved routes and the share sheet.',
    startOn: '2026-08-03',
    endOn: '2026-08-28',
    status: 'completed',
  },
  {
    id: 'cyc_nav_24',
    projectId: 'prj_nav',
    projectKey: 'NAV',
    name: 'Navigator Cycle 24',
    goal: 'Offline maps and the trip canvas rewrite.',
    startOn: '2026-09-01',
    endOn: '2026-09-26',
    status: 'active',
  },
  {
    id: 'cyc_lth_12',
    projectId: 'prj_lth',
    projectKey: 'LTH',
    name: 'Lighthouse Cycle 12',
    goal: 'Partner webhooks v2 and token rotation.',
    startOn: '2026-09-01',
    endOn: '2026-09-26',
    status: 'active',
  },
  {
    id: 'cyc_dft_8',
    projectId: 'prj_dft',
    projectKey: 'DFT',
    name: 'Driftwood Cycle 8',
    goal: 'Background location with a visible privacy sheet.',
    startOn: '2026-09-29',
    endOn: '2026-10-24',
    status: 'planned',
  },
];

type SeedIssue = {
  n: number;
  key: string;
  title: string;
  description: string;
  status: IssueStatus;
  priority: IssuePriority;
  estimate: number | null;
  projectId: string;
  cycleId: string | null;
  assigneeId: string | null;
  reporterId: string;
  parentId?: string | null;
  labelIds: string[];
  dueOn: string | null;
  ago: number;
};

const seedIssues: SeedIssue[] = [
  {
    n: 142,
    key: 'NAV',
    title: 'Rewrite the trip canvas on a scene graph',
    description:
      'The canvas is a pile of absolutely positioned divs. Zoom and pan jitter on large trips. Rebuild on a retained scene graph so pins, legs, and labels are nodes we can hit-test.\n\nAcceptance:\n- 60fps pan on a 200-stop trip\n- Keyboard move for selected pins\n- Undo stack of 50 entries',
    status: 'in_progress',
    priority: 'urgent',
    estimate: 8,
    projectId: 'prj_nav',
    cycleId: 'cyc_nav_24',
    assigneeId: 'usr_priya',
    reporterId: 'usr_maya',
    labelIds: ['lbl_feat', 'lbl_perf'],
    dueOn: '2026-09-22',
    ago: 12,
  },
  {
    n: 138,
    key: 'NAV',
    title: 'Offline map tiles for saved regions',
    description:
      'Let a traveler download a city bounding box. Store MBTiles in OPFS. Fail closed if the region is larger than 250MB.',
    status: 'in_progress',
    priority: 'high',
    estimate: 5,
    projectId: 'prj_nav',
    cycleId: 'cyc_nav_24',
    assigneeId: 'usr_priya',
    reporterId: 'usr_jonah',
    labelIds: ['lbl_feat'],
    dueOn: '2026-09-25',
    ago: 9,
  },
  {
    n: 129,
    key: 'NAV',
    title: 'Share sheet copies a read-only trip link',
    description:
      'Public links should strip live location. Expiry default 7 days. Add a revoke button on the trip page.',
    status: 'in_review',
    priority: 'high',
    estimate: 3,
    projectId: 'prj_nav',
    cycleId: 'cyc_nav_24',
    assigneeId: 'usr_theo',
    reporterId: 'usr_maya',
    labelIds: ['lbl_feat', 'lbl_ux'],
    dueOn: '2026-09-16',
    ago: 18,
  },
  {
    n: 121,
    key: 'NAV',
    title: 'Search results flash empty on slow networks',
    description:
      'The first paint after debounce is an empty state, then results arrive. Keep the previous list and show a thin progress bar.',
    status: 'todo',
    priority: 'medium',
    estimate: 2,
    projectId: 'prj_nav',
    cycleId: 'cyc_nav_24',
    assigneeId: 'usr_theo',
    reporterId: 'usr_priya',
    labelIds: ['lbl_bug', 'lbl_ux'],
    dueOn: null,
    ago: 6,
  },
  {
    n: 118,
    key: 'NAV',
    title: 'Keyboard shortcut map is undiscoverable',
    description: '`?` should open a palette of shortcuts. Document g then i, g then p, c for create.',
    status: 'todo',
    priority: 'low',
    estimate: 2,
    projectId: 'prj_nav',
    cycleId: 'cyc_nav_24',
    assigneeId: 'usr_theo',
    reporterId: 'usr_maya',
    labelIds: ['lbl_ux'],
    dueOn: null,
    ago: 20,
  },
  {
    n: 110,
    key: 'NAV',
    title: 'Saved routes from Cycle 23 still 404 after slug rename',
    description: 'Redirect old `/r/:uuid` URLs to `/trips/:slug`.',
    status: 'done',
    priority: 'high',
    estimate: 1,
    projectId: 'prj_nav',
    cycleId: 'cyc_nav_23',
    assigneeId: 'usr_priya',
    reporterId: 'usr_elias',
    labelIds: ['lbl_bug'],
    dueOn: null,
    ago: 40,
  },
  {
    n: 101,
    key: 'NAV',
    title: 'Empty state illustration for a brand new workspace',
    description: 'Theo has a sketch. Needs to ship before the next onboarding cohort.',
    status: 'backlog',
    priority: 'low',
    estimate: 1,
    projectId: 'prj_nav',
    cycleId: null,
    assigneeId: 'usr_theo',
    reporterId: 'usr_maya',
    labelIds: ['lbl_ux'],
    dueOn: null,
    ago: 4,
  },
  {
    n: 97,
    key: 'NAV',
    title: 'Pin clustering at city zoom',
    description: 'At z < 10, collapse pins into numbered clusters. Click expands.',
    status: 'backlog',
    priority: 'medium',
    estimate: 5,
    projectId: 'prj_nav',
    cycleId: null,
    assigneeId: null,
    reporterId: 'usr_priya',
    labelIds: ['lbl_feat', 'lbl_perf'],
    dueOn: null,
    ago: 2,
  },
  {
    n: 88,
    key: 'NAV',
    title: 'Dark theme contrast on muted labels fails WCAG',
    description: 'Muted gray on `#0c0d10` is 3.2:1. Bump to `#9aa0aa`.',
    status: 'in_review',
    priority: 'medium',
    estimate: 1,
    projectId: 'prj_nav',
    cycleId: 'cyc_nav_24',
    assigneeId: 'usr_theo',
    reporterId: 'usr_wren',
    labelIds: ['lbl_ux', 'lbl_bug'],
    dueOn: null,
    ago: 7,
  },
  {
    n: 76,
    key: 'NAV',
    title: 'Cancel abandoned trip drafts after 14 days',
    description: 'Drafts pile up in search. A nightly job should mark them cancelled and hide them from default views.',
    status: 'todo',
    priority: 'none',
    estimate: 2,
    projectId: 'prj_nav',
    cycleId: null,
    assigneeId: 'usr_samir',
    reporterId: 'usr_jonah',
    labelIds: ['lbl_debt'],
    dueOn: null,
    ago: 15,
  },
  {
    n: 54,
    key: 'LTH',
    title: 'Outbound webhooks v2 with signed payloads',
    description:
      'HMAC-SHA256 over the raw body. Header `X-Keelboard-Signature`. Users configure URL + events in settings. Retry 8 times with jitter. Never send on inactive rows.',
    status: 'in_progress',
    priority: 'high',
    estimate: 5,
    projectId: 'prj_lth',
    cycleId: 'cyc_lth_12',
    assigneeId: 'usr_elias',
    reporterId: 'usr_jonah',
    labelIds: ['lbl_feat', 'lbl_api', 'lbl_sec'],
    dueOn: '2026-09-24',
    ago: 11,
  },
  {
    n: 51,
    key: 'LTH',
    title: 'Rotate partner API tokens without downtime',
    description: 'Allow two live tokens per partner. Old token expires 24h after rotation.',
    status: 'todo',
    priority: 'high',
    estimate: 3,
    projectId: 'prj_lth',
    cycleId: 'cyc_lth_12',
    assigneeId: 'usr_elias',
    reporterId: 'usr_maya',
    labelIds: ['lbl_api', 'lbl_sec'],
    dueOn: '2026-09-20',
    ago: 8,
  },
  {
    n: 47,
    key: 'LTH',
    title: 'OpenAPI 3.1 from Zod schemas',
    description: 'Generate `/v1/openapi.json` from shared schemas so the SDK cannot drift.',
    status: 'in_review',
    priority: 'medium',
    estimate: 3,
    projectId: 'prj_lth',
    cycleId: 'cyc_lth_12',
    assigneeId: 'usr_elias',
    reporterId: 'usr_jonah',
    labelIds: ['lbl_api', 'lbl_debt'],
    dueOn: null,
    ago: 16,
  },
  {
    n: 41,
    key: 'LTH',
    title: 'Rate limit 429s have no Retry-After',
    description: 'Partners hammer /search. Add Retry-After and a documented 100 req/min default.',
    status: 'todo',
    priority: 'medium',
    estimate: 2,
    projectId: 'prj_lth',
    cycleId: 'cyc_lth_12',
    assigneeId: 'usr_wren',
    reporterId: 'usr_elias',
    labelIds: ['lbl_api', 'lbl_bug'],
    dueOn: null,
    ago: 5,
  },
  {
    n: 33,
    key: 'LTH',
    title: 'Deprecate XML export',
    description: 'Zero traffic in 90 days. Return 410 with a JSON body pointing at CSV.',
    status: 'backlog',
    priority: 'low',
    estimate: 1,
    projectId: 'prj_lth',
    cycleId: null,
    assigneeId: null,
    reporterId: 'usr_elias',
    labelIds: ['lbl_debt', 'lbl_api'],
    dueOn: null,
    ago: 22,
  },
  {
    n: 28,
    key: 'LTH',
    title: 'Partner sandbox workspace',
    description: 'A sealed Harbor Studio clone that resets nightly. No production data.',
    status: 'backlog',
    priority: 'medium',
    estimate: 8,
    projectId: 'prj_lth',
    cycleId: null,
    assigneeId: 'usr_samir',
    reporterId: 'usr_maya',
    labelIds: ['lbl_feat'],
    dueOn: null,
    ago: 30,
  },
  {
    n: 19,
    key: 'KEEL',
    title: 'Seat overage emails fire twice',
    description: 'The billing cron is not idempotent. Dedupe on (workspace, period).',
    status: 'in_progress',
    priority: 'urgent',
    estimate: 2,
    projectId: 'prj_keel',
    cycleId: null,
    assigneeId: 'usr_samir',
    reporterId: 'usr_maya',
    labelIds: ['lbl_bug', 'lbl_bill'],
    dueOn: '2026-09-15',
    ago: 3,
  },
  {
    n: 17,
    key: 'KEEL',
    title: 'Annual plan proration is off by one day',
    description: 'Finance caught it on Harbor Studio itself. Add a golden test for a leap year.',
    status: 'todo',
    priority: 'high',
    estimate: 3,
    projectId: 'prj_keel',
    cycleId: null,
    assigneeId: 'usr_samir',
    reporterId: 'usr_jonah',
    labelIds: ['lbl_bug', 'lbl_bill'],
    dueOn: '2026-09-18',
    ago: 10,
  },
  {
    n: 14,
    key: 'KEEL',
    title: 'Export invoices as PDF',
    description: 'Customers want a PDF, not only HTML. Use a deterministic renderer, no headless Chrome.',
    status: 'backlog',
    priority: 'medium',
    estimate: 5,
    projectId: 'prj_keel',
    cycleId: null,
    assigneeId: null,
    reporterId: 'usr_maya',
    labelIds: ['lbl_feat', 'lbl_bill'],
    dueOn: null,
    ago: 14,
  },
  {
    n: 11,
    key: 'KEEL',
    title: 'SSO via OIDC for workspace owners',
    description: 'Google and Okta to start. Map groups to Keelboard roles.',
    status: 'backlog',
    priority: 'high',
    estimate: 8,
    projectId: 'prj_keel',
    cycleId: null,
    assigneeId: 'usr_jonah',
    reporterId: 'usr_maya',
    labelIds: ['lbl_feat', 'lbl_sec'],
    dueOn: null,
    ago: 45,
  },
  {
    n: 9,
    key: 'KEEL',
    title: 'Audit log export',
    description: 'CSV of the last 90 days of admin actions. Required for two design partners.',
    status: 'todo',
    priority: 'medium',
    estimate: 3,
    projectId: 'prj_keel',
    cycleId: null,
    assigneeId: 'usr_wren',
    reporterId: 'usr_jonah',
    labelIds: ['lbl_feat', 'lbl_sec'],
    dueOn: null,
    ago: 19,
  },
  {
    n: 36,
    key: 'DFT',
    title: 'Background location privacy sheet',
    description:
      'iOS 18 will reject the current copy. Explain why we need always-on location in one screen, with a map of what is stored.',
    status: 'todo',
    priority: 'urgent',
    estimate: 3,
    projectId: 'prj_dft',
    cycleId: 'cyc_dft_8',
    assigneeId: 'usr_noor',
    reporterId: 'usr_theo',
    labelIds: ['lbl_ios', 'lbl_ux', 'lbl_sec'],
    dueOn: '2026-09-29',
    ago: 1,
  },
  {
    n: 34,
    key: 'DFT',
    title: 'Android 15 edge-to-edge overlaps the trip header',
    description: 'Apply window insets to the map chrome. Reproduce on Pixel 9.',
    status: 'in_progress',
    priority: 'high',
    estimate: 2,
    projectId: 'prj_dft',
    cycleId: null,
    assigneeId: 'usr_noor',
    reporterId: 'usr_theo',
    labelIds: ['lbl_and', 'lbl_bug', 'lbl_ux'],
    dueOn: '2026-09-17',
    ago: 4,
  },
  {
    n: 31,
    key: 'DFT',
    title: 'Widget for next turn',
    description: 'Home screen widget. No network on the critical path — use the last cached leg.',
    status: 'backlog',
    priority: 'medium',
    estimate: 5,
    projectId: 'prj_dft',
    cycleId: 'cyc_dft_8',
    assigneeId: 'usr_noor',
    reporterId: 'usr_maya',
    labelIds: ['lbl_feat', 'lbl_ios', 'lbl_and'],
    dueOn: null,
    ago: 13,
  },
  {
    n: 22,
    key: 'DFT',
    title: 'Crash on cold start when the token is expired',
    description: 'Auth interceptor retries into a loop. If refresh 401s, drop to the login screen once.',
    status: 'in_review',
    priority: 'high',
    estimate: 2,
    projectId: 'prj_dft',
    cycleId: null,
    assigneeId: 'usr_noor',
    reporterId: 'usr_elias',
    labelIds: ['lbl_bug', 'lbl_ios'],
    dueOn: null,
    ago: 8,
  },
  {
    n: 18,
    key: 'DFT',
    title: 'Haptic pattern for arrival',
    description: 'Short double tap. Disable when Reduce Motion is on.',
    status: 'done',
    priority: 'low',
    estimate: 1,
    projectId: 'prj_dft',
    cycleId: null,
    assigneeId: 'usr_theo',
    reporterId: 'usr_noor',
    labelIds: ['lbl_ux'],
    dueOn: null,
    ago: 28,
  },
  {
    n: 12,
    key: 'MAR',
    title: 'Impersonation requires a reason and a 30 minute cap',
    description: 'Support has been staying impersonated. Force a ticket id and auto-revert.',
    status: 'in_progress',
    priority: 'high',
    estimate: 3,
    projectId: 'prj_mar',
    cycleId: null,
    assigneeId: 'usr_maya',
    reporterId: 'usr_jonah',
    labelIds: ['lbl_sec', 'lbl_feat'],
    dueOn: '2026-09-19',
    ago: 6,
  },
  {
    n: 8,
    key: 'MAR',
    title: 'Customer lookup by invoice number',
    description: 'Support currently greps Slack. Add a typeahead on /customers.',
    status: 'todo',
    priority: 'medium',
    estimate: 2,
    projectId: 'prj_mar',
    cycleId: null,
    assigneeId: 'usr_samir',
    reporterId: 'usr_maya',
    labelIds: ['lbl_feat'],
    dueOn: null,
    ago: 9,
  },
  {
    n: 6,
    key: 'MAR',
    title: 'Delete a workspace and all child rows',
    description: 'Soft-delete for 14 days, then hard delete. Document the order in the runbook.',
    status: 'backlog',
    priority: 'high',
    estimate: 5,
    projectId: 'prj_mar',
    cycleId: null,
    assigneeId: 'usr_samir',
    reporterId: 'usr_jonah',
    labelIds: ['lbl_feat', 'lbl_sec'],
    dueOn: null,
    ago: 21,
  },
  {
    n: 4,
    key: 'MAR',
    title: 'Notes on a customer should be visible to support only',
    description: 'Do not leak into partner API. Add a `visibility=internal` flag.',
    status: 'done',
    priority: 'medium',
    estimate: 2,
    projectId: 'prj_mar',
    cycleId: null,
    assigneeId: 'usr_elias',
    reporterId: 'usr_maya',
    labelIds: ['lbl_sec'],
    dueOn: null,
    ago: 33,
  },
  {
    n: 21,
    key: 'BCN',
    title: 'Status page does not flip to degraded on 5xx burn',
    description: 'If 5xx > 2% for 5 minutes, mark the Navigator component degraded. Page Wren.',
    status: 'in_progress',
    priority: 'high',
    estimate: 3,
    projectId: 'prj_bcn',
    cycleId: null,
    assigneeId: 'usr_wren',
    reporterId: 'usr_jonah',
    labelIds: ['lbl_bug', 'lbl_perf'],
    dueOn: '2026-09-16',
    ago: 2,
  },
  {
    n: 16,
    key: 'BCN',
    title: 'Trace sampling is 100% in production',
    description: 'That bill is not a joke. Sample 5% except on error traces.',
    status: 'todo',
    priority: 'urgent',
    estimate: 2,
    projectId: 'prj_bcn',
    cycleId: null,
    assigneeId: 'usr_wren',
    reporterId: 'usr_samir',
    labelIds: ['lbl_perf', 'lbl_debt'],
    dueOn: '2026-09-15',
    ago: 1,
  },
  {
    n: 13,
    key: 'BCN',
    title: 'SLI dashboard for search latency',
    description: 'p50/p95/p99 on the search path. Burn-rate alert at 2x.',
    status: 'todo',
    priority: 'medium',
    estimate: 3,
    projectId: 'prj_bcn',
    cycleId: null,
    assigneeId: 'usr_wren',
    reporterId: 'usr_priya',
    labelIds: ['lbl_feat', 'lbl_perf'],
    dueOn: null,
    ago: 17,
  },
  {
    n: 7,
    key: 'BCN',
    title: 'Redact emails from trace attributes',
    description: 'We log `user.email` on the auth span. Hash it.',
    status: 'in_review',
    priority: 'high',
    estimate: 1,
    projectId: 'prj_bcn',
    cycleId: null,
    assigneeId: 'usr_wren',
    reporterId: 'usr_elias',
    labelIds: ['lbl_sec', 'lbl_bug'],
    dueOn: null,
    ago: 5,
  },
  {
    n: 3,
    key: 'BCN',
    title: 'On-call runbook for API 500s',
    description: 'Wiki page with dashboards, common causes, and who to page after 15 minutes.',
    status: 'done',
    priority: 'medium',
    estimate: 2,
    projectId: 'prj_bcn',
    cycleId: null,
    assigneeId: 'usr_wren',
    reporterId: 'usr_jonah',
    labelIds: ['lbl_feat'],
    dueOn: null,
    ago: 50,
  },
  {
    n: 64,
    key: 'NAV',
    title: 'Comment reactions',
    description: 'Ship +1 and eyes. No custom emoji in v1.',
    status: 'cancelled',
    priority: 'none',
    estimate: 3,
    projectId: 'prj_nav',
    cycleId: null,
    assigneeId: null,
    reporterId: 'usr_theo',
    labelIds: ['lbl_feat'],
    dueOn: null,
    ago: 60,
  },
  {
    n: 55,
    key: 'NAV',
    title: 'CSV import for stops',
    description: 'lat,lng,name. Cap 500 rows. Preview before commit.',
    status: 'backlog',
    priority: 'medium',
    estimate: 3,
    projectId: 'prj_nav',
    cycleId: null,
    assigneeId: 'usr_priya',
    reporterId: 'usr_maya',
    labelIds: ['lbl_feat'],
    dueOn: null,
    ago: 11,
  },
  {
    n: 49,
    key: 'LTH',
    title: 'Idempotency-Key on POST /trips',
    description: 'Partners retry. Store the key for 24h.',
    status: 'todo',
    priority: 'high',
    estimate: 3,
    projectId: 'prj_lth',
    cycleId: 'cyc_lth_12',
    assigneeId: 'usr_elias',
    reporterId: 'usr_jonah',
    labelIds: ['lbl_api'],
    dueOn: '2026-09-23',
    ago: 7,
  },
  {
    n: 25,
    key: 'KEEL',
    title: 'Usage-based overage for Lighthouse',
    description: 'Meter partner calls. Soft cap then hard cap. Show a chart on the billing page.',
    status: 'backlog',
    priority: 'high',
    estimate: 8,
    projectId: 'prj_keel',
    cycleId: null,
    assigneeId: 'usr_samir',
    reporterId: 'usr_maya',
    labelIds: ['lbl_feat', 'lbl_bill', 'lbl_api'],
    dueOn: null,
    ago: 24,
  },
  {
    n: 40,
    key: 'DFT',
    title: 'Offline trip list',
    description: 'Mirror the last 20 trips in SQLite. Conflict policy: server wins on metadata, client wins on local notes.',
    status: 'todo',
    priority: 'medium',
    estimate: 5,
    projectId: 'prj_dft',
    cycleId: 'cyc_dft_8',
    assigneeId: 'usr_noor',
    reporterId: 'usr_priya',
    labelIds: ['lbl_feat', 'lbl_ios', 'lbl_and'],
    dueOn: null,
    ago: 3,
  },
];

function issueFromSeed(row: SeedIssue): Issue {
  return {
    id: `iss_${row.key.toLowerCase()}_${row.n}`,
    number: row.n,
    identifier: `${row.key}-${row.n}`,
    title: row.title,
    description: row.description,
    status: row.status,
    priority: row.priority,
    estimate: row.estimate,
    projectId: row.projectId,
    projectKey: row.key,
    cycleId: row.cycleId,
    assigneeId: row.assigneeId,
    reporterId: row.reporterId,
    parentId: row.parentId ?? null,
    labelIds: row.labelIds,
    dueOn: row.dueOn,
    createdAt: isoDaysAgo(row.ago, 9),
    updatedAt: isoDaysAgo(Math.max(0, row.ago - 1), 16),
  };
}

const issues: Issue[] = seedIssues.map(issueFromSeed);

const comments: Comment[] = [
  {
    id: 'cmt_1',
    issueId: 'iss_nav_142',
    authorId: 'usr_theo',
    body: 'I have a prototype with a camera node and a layer for pins. Happy to pair on hit-testing.',
    createdAt: isoDaysAgo(10, 11),
  },
  {
    id: 'cmt_2',
    issueId: 'iss_nav_142',
    authorId: 'usr_priya',
    body: 'Taking it. Will land the graph without the undo stack first so we can feel pan.',
    createdAt: isoDaysAgo(9, 15),
  },
  {
    id: 'cmt_3',
    issueId: 'iss_lth_54',
    authorId: 'usr_jonah',
    body: 'Signature header must be documented before we flip any partner. No silent schema changes.',
    createdAt: isoDaysAgo(8, 10),
  },
  {
    id: 'cmt_4',
    issueId: 'iss_keel_19',
    authorId: 'usr_maya',
    body: 'Finance is getting copies. Please ship the dedupe today if you can.',
    createdAt: isoDaysAgo(2, 8),
  },
  {
    id: 'cmt_5',
    issueId: 'iss_dft_36',
    authorId: 'usr_theo',
    body: 'Copy is in Figma under Driftwood / Privacy. Keep the map. Lose the jargon.',
    createdAt: isoDaysAgo(1, 13),
  },
  {
    id: 'cmt_6',
    issueId: 'iss_bcn_16',
    authorId: 'usr_samir',
    body: 'The bill for August is in the thread. Sample errors at 100%, the rest at 5%.',
    createdAt: isoDaysAgo(1, 17),
  },
  {
    id: 'cmt_7',
    issueId: 'iss_nav_129',
    authorId: 'usr_elias',
    body: 'Public links currently include the live channel. Strip it in the serializer, not the UI.',
    createdAt: isoDaysAgo(4, 12),
  },
  {
    id: 'cmt_8',
    issueId: 'iss_mar_12',
    authorId: 'usr_jonah',
    body: 'Cap at 30 minutes even if they type a reason. Write the reason to the audit log.',
    createdAt: isoDaysAgo(5, 9),
  },
];

const views: View[] = [
  {
    id: 'view_urgent',
    name: 'Urgent & open',
    description: 'Anything urgent that is not done or cancelled.',
    ownerId: 'usr_maya',
    filter: { priority: ['urgent'], status: ['backlog', 'todo', 'in_progress', 'in_review'] },
  },
  {
    id: 'view_priya',
    name: "Priya's cycle",
    description: 'Navigator work assigned to Priya in the active cycle.',
    ownerId: 'usr_priya',
    filter: { assignee: 'usr_priya', project: 'NAV' },
  },
  {
    id: 'view_bugs',
    name: 'Open bugs',
    description: 'Bugs across every project.',
    ownerId: 'usr_jonah',
    filter: { status: ['backlog', 'todo', 'in_progress', 'in_review'] },
  },
  {
    id: 'view_unassigned',
    name: 'Unassigned',
    description: 'Nobody owns these yet.',
    ownerId: 'usr_jonah',
    filter: { assignee: 'none' },
  },
  {
    id: 'view_mobile',
    name: 'Mobile this month',
    description: 'Driftwood issues.',
    ownerId: 'usr_noor',
    filter: { project: 'DFT' },
  },
];

const wiki: WikiPage[] = [
  {
    id: 'wiki_eng',
    slug: 'engineering-handbook',
    title: 'Engineering handbook',
    authorId: 'usr_jonah',
    updatedAt: isoDaysAgo(4, 11),
    body: `# Engineering handbook

Harbor Studio ships in two-week cycles. The board is the source of truth — if it is not an issue, it is not work.

## How we plan

1. Maya drafts the cycle goal on the Friday before start.
2. Leads pull from the backlog until the estimate sum is honest, not optimistic.
3. We freeze scope on Tuesday of week one unless something is on fire.

## How we ship

- Main is always deployable.
- Feature flags for anything that touches billing or auth.
- A pull request needs one review from outside the author's team.

## Severity

| Sev | Meaning | Response |
| --- | --- | --- |
| 1 | Payments or auth down | Page immediately |
| 2 | A core flow is wrong for many users | Fix this cycle |
| 3 | Annoyance with a workaround | Backlog |

## Demo credentials

Local development uses \`maya@harbor.studio\` / \`keelboard\`. That password is not a production secret.
`,
  },
  {
    id: 'wiki_api',
    slug: 'lighthouse-api',
    title: 'Lighthouse API notes',
    authorId: 'usr_elias',
    updatedAt: isoDaysAgo(2, 15),
    body: `# Lighthouse API

Public base path is \`/v1\`.

Partners authenticate with a bearer token. Tokens are hashed at rest. Rotation keeps the previous token alive for 24 hours (see LTH-51).

## Webhooks

Users configure outbound URLs in Settings → Webhooks. We POST JSON they asked for. We do not call URLs that are not stored on an active webhook row.

Payloads are signed with HMAC-SHA256. The header is \`X-Keelboard-Signature\`.

## Idempotency

POST /trips honors \`Idempotency-Key\` for 24 hours.
`,
  },
  {
    id: 'wiki_oncall',
    slug: 'oncall-api-500',
    title: 'On-call: API 500s',
    authorId: 'usr_wren',
    updatedAt: isoDaysAgo(12, 8),
    body: `# On-call: API 500s

1. Open Beacon → SLI dashboard.
2. If p95 > 800ms and 5xx > 2%, flip Navigator to degraded.
3. Check the last deploy. Rollback if it is younger than 30 minutes.
4. If auth spans show refresh loops, see DFT-22.
5. After 15 minutes, page Jonah.

Do not restart Postgres "to see if it helps".
`,
  },
  {
    id: 'wiki_product',
    slug: 'navigator-principles',
    title: 'Navigator principles',
    authorId: 'usr_maya',
    updatedAt: isoDaysAgo(20, 10),
    body: `# Navigator principles

- A trip is a document, not a feed.
- Live location is opt-in and easy to revoke.
- Empty states teach the product, they do not apologize.
- Performance is a feature. A 200-stop trip must pan.

Cycle 24 is the canvas rewrite and offline tiles. Do not sneak in reactions (NAV-64 is cancelled on purpose).
`,
  },
  {
    id: 'wiki_billing',
    slug: 'billing-runbook',
    title: 'Billing runbook',
    authorId: 'usr_samir',
    updatedAt: isoDaysAgo(6, 14),
    body: `# Billing runbook

Seat overages must be idempotent per (workspace, period). If a customer is billed twice, refund and file KEEL-19.

Annual proration uses a 365-day year except leap years, which use 366. There is a golden test; do not "simplify" it.
`,
  },
];

const activity: Activity[] = [
  {
    id: 'act_1',
    type: 'issue.status_changed',
    actorId: 'usr_priya',
    issueId: 'iss_nav_142',
    message: 'Priya Shah moved NAV-142 to In progress',
    createdAt: isoDaysAgo(9, 15),
  },
  {
    id: 'act_2',
    type: 'issue.commented',
    actorId: 'usr_theo',
    issueId: 'iss_nav_142',
    message: 'Theo Park commented on NAV-142',
    createdAt: isoDaysAgo(10, 11),
  },
  {
    id: 'act_3',
    type: 'issue.created',
    actorId: 'usr_samir',
    issueId: 'iss_bcn_16',
    message: 'Samir Cole created BCN-16 Trace sampling is 100% in production',
    createdAt: isoDaysAgo(1, 16),
  },
  {
    id: 'act_4',
    type: 'issue.assigned',
    actorId: 'usr_jonah',
    issueId: 'iss_keel_19',
    message: 'Jonah Reed assigned KEEL-19 to Samir Cole',
    createdAt: isoDaysAgo(3, 9),
  },
  {
    id: 'act_5',
    type: 'cycle.started',
    actorId: 'usr_maya',
    issueId: null,
    message: 'Maya Chen started Navigator Cycle 24',
    createdAt: isoDaysAgo(13, 10),
  },
  {
    id: 'act_6',
    type: 'issue.status_changed',
    actorId: 'usr_theo',
    issueId: 'iss_nav_129',
    message: 'Theo Park moved NAV-129 to In review',
    createdAt: isoDaysAgo(2, 18),
  },
  {
    id: 'act_7',
    type: 'wiki.updated',
    actorId: 'usr_elias',
    issueId: null,
    message: 'Elias Ward updated Lighthouse API notes',
    createdAt: isoDaysAgo(2, 15),
  },
  {
    id: 'act_8',
    type: 'issue.status_changed',
    actorId: 'usr_noor',
    issueId: 'iss_dft_34',
    message: 'Noor Alvi moved DFT-34 to In progress',
    createdAt: isoDaysAgo(3, 12),
  },
  {
    id: 'act_9',
    type: 'issue.created',
    actorId: 'usr_theo',
    issueId: 'iss_dft_36',
    message: 'Theo Park created DFT-36 Background location privacy sheet',
    createdAt: isoDaysAgo(1, 11),
  },
  {
    id: 'act_10',
    type: 'issue.status_changed',
    actorId: 'usr_wren',
    issueId: 'iss_bcn_7',
    message: 'Wren Solis moved BCN-7 to In review',
    createdAt: isoDaysAgo(4, 17),
  },
];

const notifications: Notification[] = [
  {
    id: 'ntf_1',
    userId: 'usr_maya',
    title: 'KEEL-19 is urgent',
    body: 'Seat overage emails fire twice — Samir is on it.',
    href: '/issues/KEEL-19',
    read: false,
    createdAt: isoDaysAgo(2, 8),
  },
  {
    id: 'ntf_2',
    userId: 'usr_maya',
    title: 'NAV-142 moved to In progress',
    body: 'Priya started the trip canvas rewrite.',
    href: '/issues/NAV-142',
    read: false,
    createdAt: isoDaysAgo(9, 15),
  },
  {
    id: 'ntf_3',
    userId: 'usr_maya',
    title: 'Cycle 24 is at mid-point',
    body: 'Offline tiles and the canvas are both still open.',
    href: '/cycles/cyc_nav_24',
    read: true,
    createdAt: isoDaysAgo(1, 9),
  },
  {
    id: 'ntf_4',
    userId: 'usr_priya',
    title: 'Theo commented on NAV-142',
    body: 'Prototype with a camera node is ready to pair.',
    href: '/issues/NAV-142',
    read: false,
    createdAt: isoDaysAgo(10, 11),
  },
  {
    id: 'ntf_5',
    userId: 'usr_priya',
    title: 'NAV-121 assigned to Theo',
    body: 'Search empty flash on slow networks.',
    href: '/issues/NAV-121',
    read: true,
    createdAt: isoDaysAgo(6, 10),
  },
  {
    id: 'ntf_6',
    userId: 'usr_jonah',
    title: 'BCN-16 is urgent',
    body: 'Trace sampling is 100% in production.',
    href: '/issues/BCN-16',
    read: false,
    createdAt: isoDaysAgo(1, 16),
  },
];

const webhooks: Webhook[] = [
  {
    id: 'wh_1',
    name: 'Incident channel (disabled in demo)',
    url: 'https://example.com/hooks/keelboard-incidents',
    events: ['issue.created', 'issue.updated'],
    active: false,
    secret: 'demo_secret_not_for_production',
  },
];

const counters: Record<string, number> = {};
for (const issue of issues) {
  counters[issue.projectKey] = Math.max(counters[issue.projectKey] ?? 0, issue.number);
}

export function buildSeed(): Store {
  return {
    users: structuredClone(users),
    teams: structuredClone(teams),
    projects: structuredClone(projects),
    labels: structuredClone(labels),
    issues: structuredClone(issues),
    comments: structuredClone(comments),
    cycles: structuredClone(cycles),
    views: structuredClone(views),
    wiki: structuredClone(wiki),
    activity: structuredClone(activity),
    notifications: structuredClone(notifications),
    webhooks: structuredClone(webhooks),
    counters: { ...counters },
  };
}
